// app/layout.tsx
import './globals.css'; // Tailwind or other global styles
import { Geist } from 'next/font/google';
import { QueryProvider } from './provider/query-provider';

const geist = Geist({ subsets: ['latin'] });

export const metadata = {
  title: 'MK Homes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.className} antialiased`}>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
