

import { useAuth } from '@/hooks/useAuth';
import TeamList from '@/components/portal/team/TeamList';
import Link from 'next/link';
import { LocationBoard } from '@/components/portal/common/LocationBoard';


export const metadata = {
  title: "All Teams | MK Home Constructions",
  description: "Generated by create next app",
};
const TeamPage = () => {

  return (
    <div>


      <div className="px-8 ">
  <LocationBoard/>
        <TeamList />

      </div>
    </div>
  );
};

export default TeamPage;
