import AddNewForm from '@/components/portal/team/AddNewForm'
import React from 'react'
export const metadata = {
  title: "Team Add",
  description: "Generated by create next app",
};

const page = () => {
  
  return (
    <div className=''>
  
        <AddNewForm/>
    </div>    
  )
}

export default page